"""Prepare Dehejia and Wahba (1999) replication data.

Run from the course root:

    python assignments/code/dehejia-wahba-exam-starter.py

The script downloads the public NBER text files, assigns column names, and
writes clean CSV files to assignments/data/dehejia_wahba.

Students should use the generated CSV files for the take-home exam. The
econometric estimates are intentionally not implemented here.
"""

from __future__ import annotations

from pathlib import Path
from urllib.request import urlopen
import io

import pandas as pd


BASE_URL = "https://users.nber.org/~rdehejia/data"

SOURCE_FILES = {
    "nsw_dw_treated": "nswre74_treated.txt",
    "nsw_dw_control": "nswre74_control.txt",
    "cps": "cps_controls.txt",
    "cps2": "cps2_controls.txt",
    "cps3": "cps3_controls.txt",
    "psid": "psid_controls.txt",
    "psid2": "psid2_controls.txt",
    "psid3": "psid3_controls.txt",
}

COLUMNS = [
    "treat",
    "age",
    "educ",
    "black",
    "hispanic",
    "married",
    "nodegree",
    "re74",
    "re75",
    "re78",
]

OUT_DIR = Path(__file__).resolve().parents[1] / "data" / "dehejia_wahba"
RAW_DIR = OUT_DIR / "raw"


def download_raw_files() -> None:
    """Download the original text files from Rajeev Dehejia's NBER page."""

    RAW_DIR.mkdir(parents=True, exist_ok=True)

    for label, filename in SOURCE_FILES.items():
        url = f"{BASE_URL}/{filename}"
        out_path = RAW_DIR / filename

        with urlopen(url, timeout=30) as response:
            raw = response.read()

        out_path.write_bytes(raw)
        print(f"Downloaded {label:14s} -> {out_path}")


def read_raw_file(filename: str, sample: str) -> pd.DataFrame:
    """Read one whitespace-delimited source file and add a sample label."""

    raw_path = RAW_DIR / filename
    text = raw_path.read_text(encoding="utf-8")
    df = pd.read_csv(io.StringIO(text), sep=r"\s+", header=None, names=COLUMNS)
    df["sample"] = sample

    integer_columns = [
        "treat",
        "age",
        "educ",
        "black",
        "hispanic",
        "married",
        "nodegree",
    ]
    for col in integer_columns:
        df[col] = df[col].astype(int)

    return df


def write_dataset(filename: str, parts: list[pd.DataFrame]) -> None:
    """Concatenate dataframes and write one clean CSV."""

    df = pd.concat(parts, ignore_index=True)
    out_path = OUT_DIR / filename
    df.to_csv(out_path, index=False)
    counts = df.groupby(["sample", "treat"]).size()
    print(f"Wrote {out_path} with shape {df.shape}")
    print(counts.to_string())


def build_clean_csvs() -> None:
    """Create the cleaned datasets used in the exam."""

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    nsw_treated = read_raw_file(SOURCE_FILES["nsw_dw_treated"], "nsw_treated")
    nsw_control = read_raw_file(SOURCE_FILES["nsw_dw_control"], "nsw_control")
    cps = read_raw_file(SOURCE_FILES["cps"], "cps")
    cps2 = read_raw_file(SOURCE_FILES["cps2"], "cps2")
    cps3 = read_raw_file(SOURCE_FILES["cps3"], "cps3")
    psid = read_raw_file(SOURCE_FILES["psid"], "psid")
    psid2 = read_raw_file(SOURCE_FILES["psid2"], "psid2")
    psid3 = read_raw_file(SOURCE_FILES["psid3"], "psid3")

    write_dataset("nsw_dw_experimental.csv", [nsw_treated, nsw_control])
    write_dataset("nsw_treated_cps.csv", [nsw_treated, cps])
    write_dataset("nsw_treated_cps2.csv", [nsw_treated, cps2])
    write_dataset("nsw_treated_cps3.csv", [nsw_treated, cps3])
    write_dataset("nsw_treated_psid.csv", [nsw_treated, psid])
    write_dataset("nsw_treated_psid2.csv", [nsw_treated, psid2])
    write_dataset("nsw_treated_psid3.csv", [nsw_treated, psid3])

    readme = OUT_DIR / "README.md"
    readme.write_text(
        "# Dehejia and Wahba replication data\n\n"
        "Generated by `assignments/code/dehejia-wahba-exam-starter.py` from "
        "the NBER data page at https://users.nber.org/~rdehejia/nswdata2.html.\n\n"
        "Column order: `treat`, `age`, `educ`, `black`, `hispanic`, "
        "`married`, `nodegree`, `re74`, `re75`, `re78`, `sample`.\n\n"
        "The NBER page requests citation of Dehejia and Wahba (1999), "
        "Dehejia and Wahba (2002), and Lalonde (1986). The data are "
        "distributed for attributable non-commercial use.\n",
        encoding="utf-8",
    )


def main() -> None:
    download_raw_files()
    build_clean_csvs()


if __name__ == "__main__":
    main()
